### ISSUE TITLE
Registration_form problem 

### ISSUE THREAD

**Issue by deva59** [govardhan666/Registration_Form#1]
![Screenshot (718)](https://github.com/govardhan666/Registration_Form/assets/129718974/1d900c3c-d197-45e3-a328-73b5a3681e5a)

Hi sir I'm Devendra 
               i m getting this error-Cannot POST /sign_up please tell me how to solve this message.

**Comment by govardhan666** [comment]
First of all, thank you deva for raising your issue here. But I can't be able to solve your error just by seeing one line. Can you please share your full codes and error screenshots.

**Comment by govardhan666** [comment]
As you not responded even after one week, I am going to close this issue.
Thank you!
